export const USER_DETAILS = "USER_DETAILS";
export const DISPLAY_NOTIFICATION = "DISPLAY_NOTIFICATION";

export const BANNER_LIST = "BANNER_LIST";
export const CATEGORY_LIST = "CATEGORY_LIST";
export const MODEL_LIST = "MODEL_LIST";
export const SELECT_BANNER = "SELECT_BANNER";
export const SELECT_CATEGORY = "SELECT_CATEGORY";
export const SELECT_TYPE = "SELECT_TYPE";
export const SELECT_MODEL = "SELECT_MODEL";

export const SPECIFICATIONS = "SPECIFICATIONS";
